version: '3.7'
services:
  client:
    build: ./client
    image: client
    container_name: client
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    ports:
      - '3001:3000' # <local port>:<docker port>
    volumes:
      - ./client:/app:cached
    depends_on:
      - node

  node:
    build: ./server
    image: node
    container_name: node
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    ports:
      - '3000:3000' # <local port>:<docker port>
    volumes:
      - ./server:/app:cached
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4-rc
    container_name: mongodb
    restart: always
    tty: true
    ports:
      - '27017:27017' # <local port>:<docker port>
    volumes:
      - mongodb:/data/mongo/db   
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'

volumes:
    mongodb: